spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jwt
    username: root
    password: root@18127023
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
